services:
  dns:
    build:
      context: ./dns
      dockerfile: Dockerfile
    container_name: sprint1-dns
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - app_network
    
  email:
    build:
      context: ./email
      dockerfile: Dockerfile
    container_name: sprint1-email
    ports:
        - "25:25/tcp"
        - "587:587/tcp"
        - "993:993/tcp"
        - "995:995/tcp"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
      
